version: "3"

services:
  node:
    image: node:17.0.0-alpine
    user: node
    entrypoint: node
    command: src/index.js
    tty: true
    stdin_open: true
    working_dir: /home/node
    volumes:
      - .:/home/node

  nginx:
    image: nginx:1.21.6
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/default_website.conf:/etc/nginx/conf.d/default_website.conf
      - ./nginx/default_api.conf:/etc/nginx/conf.d/default_api.conf
      - ./nginx/default_database.conf:/etc/nginx/conf.d/default_database.conf

  client:
    build: ./client
    volumes:
      - ./client/:/home/client/
    entrypoint: node index.js

  api:
    build: ./api
    volumes:
      - ./api/:/home/api/
    entrypoint: node index.js

  mongodb:
    image: mongo:latest # use the latest image.
    container_name: mongodb
    restart: unless-stopped
    environment: # set required env variables to access mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes: # optional to preserve database after container is deleted.
      - ./database-data:/data/db
 
  # Mongo Express Service
  mongo-express:
    image: mongo-express:latest # latest image
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
